//prepare collection
sh ~/desktop/CEP_TWM0409/file3gformat2m/file3gformat2m_run.sh
//map fields
db.cep3g_insert.find({
    "record_type":{$in:["1","2"]}
},{
    "called_subs_last_ci" : 1,      //#index site
    "calling_subs_last_ci" : 1,     //#index site
    "PT_OID" : 1,
    "SITE_ID"  1,
    "_id" : 1
});

//req fields
> db.cep3g.findOne({
    "record_type":{$in:["1","2"]}
},{
    "called_number" : 1,          //^[]#index
    "called_imei" : 1,              //#index pt
    "called_imsi" : 1,              //^[]
    "called_subs_last_ci" : 1,      //#index site
    "called_subs_last_lac" : 1,     //#index site

    "calling_imei" : 1,             //#index pt
    "calling_imsi" : 1,             //^[]
    "calling_number" : 1,           //^[]
    "calling_subs_last_ci" : 1,     //#index site
    "calling_subs_last_lac" : 1,    //#index site

    "cause_for_termination" : 1,    //____$
    "charging_end_time" : 1,        //#index time
    "charging_start_time" : 1,      //#index time
    "exchange_id" : 1,              //[]
    "orig_mcz_duration" : 1,
    "radio_network_type" : 1,
    "record_type" : 1,
    "term_mcz_duration" : 1,
    "date_time" : 1,                //#index time
    "_id":1
    //,"up_flag" : 1
    //,"in_flag" : 1
});

//all fields
db.cep3g_sample.find({},
    {
        "_id" : 1,
        "acceptable_channel_codings_01" : 1,
        "acceptable_channel_codings_02" : 1,
        "acceptable_channel_codings_03" : 1,
        "acceptable_channel_codings_04" : 1,
        "acceptable_channel_codings_05" : 1,
        "acceptable_channel_codings_06" : 1,
        "acceptable_channel_codings_07" : 1,
        "acceptable_channel_codings_08" : 1,
        "add_routing_category" : 1,
        "answer_time" : 1,
        "aoc_indicator" : 1,
        "b_idle_time" : 1,
        "basic_service_code" : 1,
        "basic_service_type" : 1,
        "call_reference" :1,
        "call_reference_comp" : 1,
        "call_reference_focus" : 1,
        "call_reference_process" : 1,
        "call_reference_time" : 1,
        "call_type" : "1,
        "call_state" :1,
        "called_category" : 1,
        "called_cell_band" :1,
        "called_charging_area" : 1,
        "called_imei" :1,
        "called_imsi" :1,
        "called_modify_parameters_01" :1,
        "called_modify_parameters_02" :1,
        "called_modify_parameters_03" :1,
        "called_modify_parameters_04" :1,
        "called_modify_parameters_05" :1,
        "called_modify_parameters_06" :1,
        "called_modify_parameters_07" :1,
        "called_ms_classmark" : 1,
        "called_msrn" :1,
        "called_msrn_npi" : 1,
        "called_msrn_ton" : 1,
        "called_number" : 1,
        "called_number_npi" : 1,
        "called_number_ton" : 1,
        "called_subs_first_ci" : 1,
        "called_subs_first_lac" : 1,
        "called_subs_first_mcc" :1,
        "called_subs_first_mnc" :1,
        "called_subs_last_ci" : 1,
        "called_subs_last_ex_id" :1,
        "called_subs_last_ex_id_ton" : 1,
        "called_subs_last_lac" : 1,
        "called_subs_last_mcc" :1,
        "called_subs_last_mnc" :1,
        "calling_category" : 1,
        "calling_cell_band" : 1,
        "calling_charging_area" : 1,
        "calling_imei" : 1,
        "calling_imsi" : 1,
        "calling_modify_parameters_01" :1,
        "calling_modify_parameters_02" :1,
        "calling_modify_parameters_03" :1,
        "calling_modify_parameters_04" :1,
        "calling_modify_parameters_05" :1,
        "calling_modify_parameters_06" :1,
        "calling_modify_parameters_07" :1,
        "calling_ms_classmark" : 1,
        "calling_number" : 1,
        "calling_number_npi" : 1,
        "calling_number_ton" : 1,
        "calling_subs_first_ci" : 1,
        "calling_subs_first_lac" : 1,
        "calling_subs_first_mcc" : 1,
        "calling_subs_first_mnc" : 1,
        "calling_subs_last_ci" : 1,
        "calling_subs_last_ex_id" : 1,
        "calling_subs_last_ex_id_ton" : 1,
        "calling_subs_last_lac" : 1,
        "calling_subs_last_mcc" : 1,
        "calling_subs_last_mnc" : 1,
        "camel_call_reference" : 1,
        "camel_exchange_id" : 1,
        "camel_exchange_id_ton" : 1,
        "carrier_selection" : "1,
        "cause_for_termination" : 1,
        "cf_information" :1,
        "channel_rate_indicator_01" : 1,
        "channel_rate_indicator_02" : 1,
        "charging_end_time" : 1,
        "charging_start_time" :1,
        "check_sum" : 1,
        "connected_to_number" : 1,
        "connected_to_number_npi" : 1,
        "connected_to_number_ton" : 1,
        "cug_information" : 1,
        "cug_interlock_01" :1,
        "cug_interlock_02" : 1,
        "cug_outgoing_access" : 1,
        "data_volume" : 1,
        "dialled_digits" :1,
        "dialled_digits_npi" : 1,
        "dialled_digits_ton" : 1,
        "dtmf_indicator" : 1,
        "emergency_call_category_01" : 1,
        "emergency_call_category_02" : 1,
        "emergency_call_category_03" : 1,
        "emergency_call_category_04" : 1,
        "emergency_call_category_05" : 1,
        "exchange_id" : 1,
        "facility_usage_01" : 1,
        "facility_usage_02" : 1,
        "facility_usage_03" : 1,
        "facility_usage_04" : 1,
        "facility_usage_05" : 1,
        "facility_usage_06" : 1,
        "facility_usage_07" : 1,
        "facility_usage_08" : 1,
        "facility_usage_09" : 1,
        "facility_usage_10" : 1,
        "facility_usage_11" : 1,
        "facility_usage_12" : 1,
        "facility_usage_13" : 1,
        "facility_usage_14" : 1,
        "facility_usage_15" : 1,
        "facility_usage_16" : 1,
        "facility_usage_17" : 1,
        "facility_usage_18" : 1,
        "facility_usage_19" : 1,
        "facility_usage_20" : 1,
        "facility_usage_21" : 1,
        "facility_usage_22" : 1,
        "facility_usage_23" : 1,
        "facility_usage_24" : 1,
        "facility_usage_25" : 1,
        "facility_usage_26" : 1,
        "facility_usage_27" : 1,
        "forwarded_to_number" :1,
        "forwarded_to_number_ton" :1,
        "hot_billing_record_number" : 1,
        "in_bnc_connection_type" :1,
        "in_channel_allocated_time" : 1,
        "in_circuit" :1,
        "in_circuit_group" :1,
        "inside_control_plane_index" :1,
        "inside_user_plane_index" :1,
        "intermediate_charging_ind" : 1,
        "intermediate_chrg_cause_01" : 1,
        "intermediate_chrg_cause_02" : 1,
        "intermediate_chrg_cause_03" : 1,
        "intermediate_chrg_cause_04" : 1,
        "intermediate_chrg_cause_05" : 1,
        "intermediate_chrg_cause_06" : 1,
        "intermediate_chrg_cause_07" : 1,
        "intermediate_chrg_cause_08" : 1,
        "intermediate_record_number" : 1,
        "leg_call_reference" :1,
        "leg_call_reference_comp" : 1,
        "leg_call_reference_focus" : 1,
        "leg_call_reference_process" : 1,
        "loc_routing_number" :1,
        "loc_routing_number_ton" : 1,
        "ms_classmark3" : 1,
        "non_transparency_indicator" : 1,
        "npdb_query_status" : 1,
        "number_of_all_in_records" : 1,
        "number_of_ss_records" : 1,
        "orig_calling_number" :1,
        "orig_calling_number_npi" :1,
        "orig_calling_number_ton" :1,
        "orig_dialling_class" :1,
        "orig_mcz_chrg_type_01" : 1,
        "orig_mcz_chrg_type_02" : 1,
        "orig_mcz_chrg_type_03" : 1,
        "orig_mcz_chrg_type_04" : 1,
        "orig_mcz_chrg_type_05" : 1,
        "orig_mcz_duration" :1,
        "orig_mcz_duration_ten_ms" : 1,
        "orig_mcz_modify_direction" : 1,
        "orig_mcz_modify_percent" : 1,
        "orig_mcz_pulses" : 1,
        "orig_mcz_tariff_class" : 1,
        "out_bnc_connection_type" : 1,
        "out_channel_allocated_time" :1,
        "out_circuit" : "41,
        "out_circuit_group" : "251,
        "outside_control_plane_index" : 1,
        "outside_user_plane_index" : 1,
        "pic" : "FF1,
        "pni" : "FFFF1,
        "radio_network_type" : 1,
        "rate_adaption" : 1,
        "record_length" : 1,
        "record_number" : 1,
        "record_status" : 1,
        "record_type" : 1,
        "redirected_indicator" : 1,
        "redirecting_number" :1,
        "redirecting_number_npi" :1,
        "redirecting_number_ton" :1,
        "regional_subs_indicator" : 1,
        "regional_subs_location_type" : 1,
        "req_air_interface_user_rate" : 1,
        "req_fixed_nw_user_rate" : 1,
        "req_number_of_channels" : 1,
        "req_other_modem_type" : 1,
        "req_user_initiated_mod_ind" : 1,
        "routing_category" : 1,
        "routing_info" :1,
        "set_up_start_time" : 1,
        "speech_version" : 1,
        "start_time" :1,
        "stream_identifier" : 1,
        "term_mcz_chrg_type_01" :1,
        "term_mcz_chrg_type_02" :1,
        "term_mcz_chrg_type_03" :1,
        "term_mcz_chrg_type_04" :1,
        "term_mcz_chrg_type_05" :1,
        "term_mcz_duration" : 1,
        "term_mcz_duration_ten_ms" : 1,
        "term_mcz_modify_direction" :1,
        "term_mcz_modify_percent" :1,
        "term_mcz_pulses" :1,
        "term_mcz_tariff_class" :1,
        "tns_carrier_code" : 1,
        "tns_circuit_code" :1,
        "used_air_interface_user_rate" :1,
        "used_channel_coding" :1,
        "used_fixed_nw_user_rate" :1,
        "used_number_of_channels" :1,
        "used_other_modem_type" :1,
        "date_time" : 1,
        "short_called_number" :1,
        "reversed_called_number" :1,
        "short_calling_number" :1,
        "reversed_calling_number" :1,
        "short_connected_to_number" :1,
        "reversed_connected_to_number" :1,
        "short_orig_calling_number" :1,
        "reversed_orig_calling_number" :1,
        "short_redirecting_number" :1,
        "reversed_redirecting_number" :1,
        "release_time" :1
    });
