//clone

//req fields
db.siteview3g_sample.find({}, {
    "BTS_CODE": 1          //"BTS_CODE" : "RNW30",
    ,"SITE_ID": 1           //"SITE_ID" : 10001,
    ,"SITE_NAME": 1         //"SITE_NAME" : "中正仁愛",
    ,"BELONG_TO": 1         //"BELONG_TO" : "第一維運處",
    ,"CELL_NO": 1           //----------"CELL_NO" : 10361,
    ,"LAC_OD": 1            //----------"LAC_OD" : 11116,
    ,"BTS_ADDRESS" : 1      //"BTS_ADDRESS" : "台北市中正區",
    ,"_id":1
});

//assert fields
db.siteview3g_sample.find({}, {
    "SITE_ID": 1,           //"SITE_ID" : 10001,
    "CELL_NO": 1,           //----------"CELL_NO" : 10361,
    "LAC_OD": 1,            //----------"LAC_OD" : 11116,
});

//all fields
db.siteview3g_sample.findOne()
{
    "_id" : ObjectId("55123ab390b534c75ec0d58b"),
    "BTS_CODE" : "RNW30",
    "SITE_ID" : 10001,
    "SITE_NAME" : "中正仁愛",
    "BELONG_TO" : "第一維運處",
    "CELL_NO" : 10361,
    "LAC_OD" : 11116,
    "NWIS_SITE_TYPE" : "Flexi-2P",
    "SITE_NO" : 354,
    "BTS" : 12,
    "LAC" : 11116,
    "SAC" : 10361,
    "SACB" : 0,
    "RAC" : 64,
    "UARFCN" : 10713,
    "PRI_SCR_CODE" : 371,
    "PTX_PRIMARY_CPICH" : 330,
    "PT_X_PICH" : -8,
    "PRX_TARGET" : 160,
    "PRX_OFFSET" : 20,
    "PTX_TARGET" : 420,
    "PTX_OFFSET" : 10,
    "RT_FMCG_IDENTIFIER" : 5,
    "RT_FMCI_IDENTIFIER" : 1,
    "RT_FMCS_IDENTIFIER" : 58,
    "NRT_FMCG_IDENTIFIER" : 5,
    "NRT_FMCI_IDENTIFIER" : 3,
    "NRT_FMCS_IDENTIFIER" : 55,
    "DL_MAX_BIT_RATE_PSNRT" : 64,
    "UL_MAX_BIT_RATE_PSNRT" : 128,
    "DL_MIN_ALLOWED_BIT_RATE" : 16,
    "UL_MIN_ALLOWED_BIT_RATE" : 16,
    "Q_QUAL_MIN" : -22,
    "Q_RXLEV_MIN" : -58,
    "MHA" : 0,
    "CABLE_LOSS" : 30,
    "W_CEL_STATE" : 0,
    "URA_ID" : 14001,
    "LONGITUDE" : "",
    "LAT" : "",
    "ANTENNA_ANGLE" : 50,
    "ANTENNA_INCLINATION" : "4/6/0",
    "ANTENNA_HEIGHT" : 36,
    "ANTENNA_MODEL" : "HBXX-6516DS-VTM",
    "BTS_ADDRESS" : "台北市中正區",
    "BTS_PROP" : "都會區(3小時內維修)",
    "IS_VIP" : "N",
    "BTS_STATUS" : "OnAir(BI完工)",
    "IS_HSDPA_ENABLED" : 1,
    "TRANSPORT_VENDER" : "TFN",
    "TRANSPORT_VOLUMN" : 1,
    "IN_OUT_DOOR" : "OUTDOOR",
    "RNCID" : 140,
    "TRANSPORT_TYPE" : "Hybrid",
    "IS_HSUPA_ENABLED" : 1,
    "T_CELL" : 3,
    "HSPDSCH_CODE_SET" : 64800,
    "NETWORK_SPEED" : "42M",
    "MAX_NBR_OF_HSSCCH_CODES" : 3,
    "RNC_SITENO" : 140354,
    "HSDPA_64_QA_MALLOWED" : 1,
    "ANTENNA_VENDER" : "Andrew",
    "ANTENNA_HALF_POWER_ANGLE" : 65,
    "IS_D_CELL_HSDPA_ENABLED" : 1,
    "HSPA_72_USERS_PER_CELL" : 1,
    "TRANSPORT_RATE" : 200,
    "IS_TBT_ENABLED" : 1,
    "FEEDER_LESS_TYPE" : "MASTER",
    "FEEDER_LESS_SITE_ID" : "",
    "FEEDER_LESS_SITE" : "",
    "OPERATION_UNIT" : "北市南維運一課",
    "RAC_NUM" : 1,
    "REMOTE_STATION_NUMBER" : 1,
    "CLUSTER_ID" : 1100
}
